

@api = http://localhost:3000

///TIPO SERVICIOS API
#####
PUT {{api}}/tipoServicios/1
Content-Type: application/json

{
    "tipoServicio": "Desarrollo",
    "descripcion": "Desarrollo de productos tecnologicos"
}


#####
GET {{api}}/tipoServicios


###
POST {{api}}/tipoServicios
Content-Type: application/json

{
    "tipoServicio": "Desarrollo a la medida",
    "descripcion": "Solicite su sistema según las necesidades ",
    "url": "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885_1280.jpg"
}




///COTIZACIONES API
###
//Obtener todas cotizaciones
GET {{api}}/cotizaciones


###
GET {{api}}/cotizaciones/1

//Obtener cotizaciones por tipo de servicio 
###
GET {{api}}/cotizaciones/1
###
//Obtener cotizaciones por cliente
GET {{api}}/cotizaciones/1

###
//Actualizar una nueva cotizacion
PUT  {{api}}/cotizaciones/1
Content-Type: application/json

{
    "fecha" : "2023/01/23",
    "mensaje" : "Me gustaria otro servicio ",
    "idTipoServicio" : 1,
    "idCliente" : 1

}

###
//Agregar una nueva cotizacion
POST {{api}}/cotizaciones
Content-Type: application/json

{
    "fecha" : "2020-03-19",
    "mensaje" : "Me gustaria un servicio ",
    "idTipoServicio" : 1,
    "idCliente" : 1
}

###
//SERVICIOS API
GET {{api}}/servicios/

###
//Obtener un servicio por id
GET {{api}}/servicios/1

###
//Ver un servicio por fecha 

GET {{api}}/servicios/fecha

###
//Ver servicios por cliente

GET {{api}}/servicios/cliente



###
//Actualizar un servicio
PUT  {{api}}/servicios/1
Content-Type: application/json

{
    "idTipoServicio" : 1,
    "descripcion" : "Se brinda servicios de desarrollo",
    "costo": "1000",
    "fechaInicio" : "2020-11-20",
    "fechaFin": "2021-11-20",
    "idCliente" : 1
}

###
//Agregar un nuevo servicio
POST {{api}}/servicios
Content-Type: application/json

{
    "idTipoServicio" : 1,
    "descripcion" : "Se brinda servicio de consultoria",
    "costo": "1000",
    "fechaInicio" : "2020-11-20",
    "fechaFin": "2021-11-20",
    "idCliente" : 1
}


//CLIENTES API
###
POST {{api}}/cliente
Content-Type: application/json

{
    "nombre":"Federico",
    "apellido":"Torres",
    "correo":"federicotorres2109@gmail.com",
    "empresa":"K-Tech"
}


###
PUT {{api}}/cliente/1
Content-Type: application/json

{
    "nombre":"Federico",
    "apellido":"Torres",
    "correo":"federicotorres2109@gmail.com",
    "empresa":"TEC"
}





###
GET {{api}}/clientes


###
GET {{api}}/cliente/1


###


POST {{api}}/usuarios
Content-Type: application/json

{
    "correo":"Federicotorres2109@gmail.com",
    "password":"123",
    "numeroTelefono":"78261523"

}


###
GET {{api}}/usuarios



###
POST {{api}}/blog
Content-Type: application/json

{
    "nombre":"Articulo 1",
    "urlPost":"https://www.youtube.com/watch?v=6u1RHUoXIPI",
    "urlImagen":"https://www.educaciontrespuntocero.com/wp-content/uploads/2019/02/girasoles-978x652.jpg"
}


###
GET {{api}}/blogs